name: Generate Snake Animation

on:
  schedule:
    # Actualiza el gr√°fico de la serpiente cada d√≠a a medianoche UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: robpalacios1
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Push to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif
          git diff --staged --quiet || git commit -m "Generate snake animation üêç"
          git push

